import { createSchemaField } from "@formily/react";
import {
  ArrayItems,
  ArrayTable,
  DatePicker,
  FormCollapse,
  FormGrid,
  FormItem,
  FormLayout,
  FormTab,
  Input,
  NumberPicker,
  Radio,
  Select,
  Space,
  Switch,
  TimePicker,
} from "@formily/antd-v5";
import { Card, Slider } from "antd";

import type { FC } from "react";
import ReactionsSetter from "../setters/ReactionsSetter";
import {
  ApiBaseNameFormItem,
  ApiGroupFormItem,
  ApiHeadersFormItem,
  ApiOriginFormItem,
  BackgroundImageInput,
  BackgroundStyleSetter,
  BorderRadiusStyleSetter,
  BorderStyleSetter,
  BoxShadowStyleSetter,
  BoxStyleSetter,
  CollapseItem,
  ColorInput,
  ColorTypeSelect,
  ColorTypeSelect2,
  CornerInput,
  DecoratorPaddingFormItem,
  DepFieldSetFormItem,
  DisplayStyleSetter,
  DrawerSetter,
  FlexStyleSetter,
  FontStyleSetter,
  ImageInput,
  IsDarkThemeSelect,
  JsonInput,
  PositionDecoratorFormItem,
  PositionInput,
  SizeInput,
  ValueInput,
} from "./components";
import DataSourceBind from "./components/DataSourceBind";

const SchemaField2: FC<any> = createSchemaField({
  components: {
    FormItem,
    CollapseItem,
    Input,
    ValueInput,
    SizeInput,
    ColorInput,
    ImageInput,
    Card,
    PositionInput,
    CornerInput,
    BackgroundImageInput,
    BackgroundStyleSetter,
    BoxStyleSetter,
    BorderStyleSetter,
    BorderRadiusStyleSetter,
    DisplayStyleSetter,
    BoxShadowStyleSetter,
    FlexStyleSetter,
    FontStyleSetter,
    DrawerSetter,
    NumberPicker,
    DatePicker,
    TimePicker,
    Select,
    Radio,
    Slider,
    Switch,
    Space,
    ArrayItems,
    ArrayTable,
    FormCollapse,
    FormGrid,
    FormLayout,
    FormTab,
    IsDarkThemeSelect,
    ColorTypeSelect,
    ColorTypeSelect2,
    PositionDecoratorFormItem,
    JsonInput,
    DepFieldSetFormItem,
    DecoratorPaddingFormItem,
    ApiBaseNameFormItem,
    ApiGroupFormItem,
    ApiHeadersFormItem,
    ApiOriginFormItem,

    DataSourceBind,
    ReactionsSetter,
  },
});

export default SchemaField2;
